feat: design and code optimization

diff --git a/sparrow b/sparrow
--- a/sparrow
+++ b/sparrow
@@ -5,23 +5,41 @@ CUR_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)
 cd $CUR_PATH
 BATH_PATH=$(pwd)
 
+# =================================== sparrow help command ===================================
+COMMAND=$1
+if [ "${COMMAND}" = "help" ] || [ "${COMMAND}" = "--help" ] || [ "${COMMAND}" = "h" ] || [ "${COMMAND}" = "-h" ] ; then
+    # sparrow's help command
+    printf "welcome to sparrow\n"
+    printf "\n"
+    printf "1、Control all service.\n"
+    printf "(1) stop all services: ./sparrow stop\n"
+    printf "(2) start all services: ./sparrow start\n"
+    printf "(3) restart all services: ./sparrow restart\n"
+    printf "\n"
+    printf "2、Control one service.\n"
+    printf "(1) stop one service: ./sparrow stopone {service_name}\n"
+    printf "(2) start one service: ./sparrow startone {service_name}\n"
+    printf "(3) update one service: ./sparrow updateone {service_name}\n"
+    printf "\n"
+    printf "4、Container helper.\n"
+    printf "(1) enter all containers(Automatically open all required resources): ./sparrow enter\n"
+    printf "(2) enter one container: ./sparrow enter {service_name}\n"
+    printf "\n"
+    exit 0
+fi
+# =================================== sparrow help command ===================================
+
 # include sdk of sparrow.
 source .work/include/sdk.sh
 
-# before run sparrow command.
-before_sparrow_command() {
-    print_info "do before_sparrow_command..."
-
-    print_stage "check startable..."
-    if ! check_startable; then
-        print_error "check startable failed"
-        exit 1
+# do sparrow hook
+hook() {
+    # hook {hook_type} {service}
+    hook_file="$2/hooks/$1.sh"
+    if [ -f "${hook_file}" ]; then
+        print_info "do hook: ${hook_file}"
+        source "${hook_file}"
     fi
-}
-
-# after run sparrow command.
-after_sparrow_command() {
-    print_info "do after_sparrow_command..."
 }
 
 # start one service.
@@ -132,6 +150,38 @@ restart() {
     start
 }
 
+# before run sparrow command.
+before_sparrow_command() {
+    print_info "do before_sparrow_command..."
+
+    # check docker.
+    if ! docker info > /dev/null 2>&1; then
+        print_error "error: please install or start docker first."
+        exit 1
+    fi
+
+    # check ip.
+    local_ip=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | sed 's/,$//' | head -n 1)
+    if [ "$local_ip" != "$DOCKER_HOST_IP" ]; then
+        print_warn "your ip: before=$DOCKER_HOST_IP, after=$local_ip"
+
+        DOCKER_HOST_IP=$local_ip  # update environment DOCKER_HOST_IP
+        if is_mac; then
+            sed -i '' "s/^DOCKER_HOST_IP=.*/DOCKER_HOST_IP=${DOCKER_HOST_IP}/g" "${CONST_SPARROW_CONFIG_ENV_FILE}"
+        elif is_linux; then
+            sed -i "s/^DOCKER_HOST_IP=.*/DOCKER_HOST_IP=${DOCKER_HOST_IP}/g" "${CONST_SPARROW_CONFIG_ENV_FILE}"
+        else
+            print_error "your local ip changed, please modify DOCKER_HOST_IP in the ${CONST_SPARROW_CONFIG_ENV_FILE} file"
+            exit 1
+        fi
+    fi
+}
+
+# after run sparrow command.
+after_sparrow_command() {
+    print_info "do after_sparrow_command..."
+}
+
 ##################### start script exec flow #####################
 
 # before run sparrow command.
@@ -146,35 +196,19 @@ elif [ "${COMMAND}" = "restart" ]; then
     restart
 elif [ "${COMMAND}" = "stop" ]; then
     stop
-elif [ "${COMMAND}" = "startone" ]; then
+elif [ "${COMMAND}" = "startone" ] || [ "${COMMAND}" = "stopone" ] || [ "${COMMAND}" = "updateone" ]; then
     if [ "$2" == "" ]; then
         print_error "check param error: miss service param"
         exit 1
     fi
-    startone "$2"
-elif [ "${COMMAND}" = "stopone" ]; then
-    if [ "$2" == "" ]; then
-        print_error "check param error: miss service param"
-        exit 1
+
+    if [ "${COMMAND}" = "startone" ]; then
+        startone "$2"
+    elif [ "${COMMAND}" = "stopone" ]; then
+        stopone "$2"
+    elif [ "${COMMAND}" = "updateone" ]; then
+        updateone "$2"
     fi
-    stopone "$2"
-elif [ "${COMMAND}" = "updateone" ]; then
-    if [ "$2" == "" ]; then
-        print_error "check param error: miss service param"
-        exit 1
-    fi
-    updateone "$2"
-# not core commands.
-elif [ "${COMMAND}" = "clear" ]; then
-    clear_service "all"
-elif [ "${COMMAND}" = "clearone" ]; then
-    if [ "$2" == "" ]; then
-        print_error "check param error: miss service param"
-        exit 1
-    fi
-    clear_service "$2"
-elif [ "${COMMAND}" = "help" ] || [ "${COMMAND}" = "--help" ] || [ "${COMMAND}" = "h" ] || [ "${COMMAND}" = "-h" ] ; then
-    sparrow_help
 else
     echo "not support command: ${COMMAND}"
 fi
diff --git a/sparrowtool b/sparrowtool
--- a/sparrowtool
+++ b/sparrowtool
@@ -5,18 +5,51 @@ CUR_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)
 cd $CUR_PATH
 BATH_PATH=$(pwd)
 
+# =================================== sparrowtool help command ===================================
+COMMAND=$1
+if [ "${COMMAND}" = "help" ] || [ "${COMMAND}" = "--help" ] || [ "${COMMAND}" = "h" ] || [ "${COMMAND}" = "-h" ] ; then
+    printf "welcome to sparrowtool\n"
+    printf "\n"
+    printf "1、about create.\n"
+    printf "(1) create service: ./sparrowtool new -t service -s {service_name} -p port -v version\n"
+    printf "    ① params: -t(type:service) / -s(service) / -p(port) / -v(version)\n"
+    printf "    ② example 1: ./sparrowtool new -s prometheus -p 9876 -v 0.0.98\n"
+    printf "\n"
+    printf "2、about container.\n"
+    printf "(1) enter container: ./sparrowtool enter {service?}\n"
+    printf "    ① param: if you pass nothing, if will enter all containers.\n"
+    printf "    ② example 1: ./sparrowtool enter\n"
+    printf "    ② example 2: ./sparrowtool enter go\n"
+    printf "\n"
+    printf "3、about image.\n"
+    printf "(1) upload image: ./sparrowtool upload -t(type:app|basic) -s(service) -v(version) -r(replace)\n"
+    printf "    ① param: {app}means the application image, {basic}means the basic image, {service}means the name of service.\n"
+    printf "    ② example 1: ./sparrowtool upload -t basic -s etcd -v 3.5.0\n"
+    printf "(2) mupload image: ./sparrowtool mupload {service1} {service2} ...\n"
+    printf "    ① param: mupload means multi/batch upload\n"
+    printf "    ② example 1: ./sparrowtool mupload etcd kafka mysql\n"
+    printf "\n"
+    printf "4、about env.\n"
+    printf "(1) list all matched environment variables in /env file : ./sparrowtool env -l {match_pattern}\n"
+    printf "    ① param: -l(match_pattern)\n"
+    printf "    ① example 1: ./sparrowtool env -l port\n"
+    printf "\n"
+    printf "5、about clear.\n"
+    printf "(1) clear one service or all service : ./sparrowtool clear {service?}\n"
+    printf "    ① param: if you pass nothing, if will clear all services.\n"
+    printf "    ① example 1: ./sparrowtool clear\n"
+    printf "    ② example 2: ./sparrowtool clear go\n"
+    printf "\n"
+    printf "5、about tip.\n"
+    printf "(1) show all tips : ./sparrowtool tip\n"
+    printf "\n"
+    printf "========================================================\n"
+    exit 0
+fi
+# =================================== sparrowtool help command ===================================
+
 # include sdk of sparrow.
 source .work/include/sdk.sh
-
-# before run sparrowtool command.
-before_sparrowtool_command() {
-    print_stage "do before_sparrowtool_command..."
-}
-
-# after run sparrowtool command.
-after_sparrowtool_command() {
-    print_stage "do after_sparrowtool_command..."
-}
 
 # new something.
 new() {
@@ -38,7 +71,7 @@ new() {
         image_app_version=latest
         ;;
         \?)
-        echo "无效的选项: -$OPTARG" >&2
+        echo "invalid option: -$OPTARG" >&2
         exit 1
         ;;
     esac
@@ -76,6 +109,59 @@ new() {
         -e "s/{{IMAGE_BASIC_VERSION}}/$image_basic_version/g" \
         -e "s/{{IMAGE_APP_VERSION}}/$image_app_version/g" \
         "${CONST_SERVICE_EXAMPLE_DIR}/${relative_path}" > "./${service}/${relative_path}"
+    done
+}
+
+# show some tips.
+tip() {
+    # -u root: fix error(https://stackoverflow.com/questions/37836124/i-have-no-name-as-user-logging-into-jenkins-in-a-docker-container-that-uses-t)
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_go bash"
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_nginx bash"
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_mysql bash"
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_redis bash"
+
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_mysql bash -c 'mysql -u ${MYSQL_ROOT_USER} -h 127.0.0.1 -p${MYSQL_ROOT_PASSWORD} -P${MYSQL_CONTAINER_PORT} --default-character-set=utf8'"
+    echo "docker exec -w '/' -u root -it sparrow_container_${CONTAINER_NAMESPACE}_redis bash -c 'redis-cli -h 127.0.0.1 -p ${REDIS_CONTAINER_PORT} -a ${REDIS_PASSWORD}'"
+}
+
+# search the matched variables in /env file
+search_env() {
+    shift # remove the first argument: new
+    while getopts "l:" opt; do
+    case $opt in
+        l)
+        arg=$(echo "$OPTARG" | awk '{print toupper($0)}')
+        pattern=".*$arg.*"
+        ;;
+        \?)
+        echo "invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+    done
+
+    subdirectories=$(ls -l | grep '^d' | awk '{print $9}')
+
+    for dir in $subdirectories; do
+        env_file="$dir/${CONST_SPARROW_CONFIG_ENV_FILE}"
+        if [ ! -f "$env_file" ]; then
+            continue
+        fi
+
+        printf "${dir} Service\n===========================================================\n"
+        while IFS= read -r line; do
+            # ignore comments.
+            if [[ "$line" =~ ^\# ]]; then
+                continue
+            fi
+
+            if echo "$line" | grep -q "$pattern"; then
+                key=$(echo "$line" | cut -d '=' -f1)
+                value=$(echo "$line" | cut -d '=' -f2-)
+                printf "${key}=${value}\n"
+            fi
+        done < "$env_file"
+        printf "\n"
     done
 }
 
@@ -124,61 +210,38 @@ multi_upload() {
     done
 }
 
-# search the matched variables in /env file
-search_env() {
-  shift # remove the first argument: new
-  while getopts "l:" opt; do
-  case $opt in
-      l)
-      arg=$(echo "$OPTARG" | awk '{print toupper($0)}')
-      pattern=".*$arg.*"
-      ;;
-      \?)
-      echo "无效的选项: -$OPTARG" >&2
-      exit 1
-      ;;
-  esac
-  done
+# clear service, include remove container and remove images.
+clear_service() {
+    # check service param.
+    if [ "$1" == "" ]; then
+        service_list=("${ENABLE_SERVICE_LIST[@]}")  # copy the whole array
+    else
+        service_list=($1)
+    fi
 
-  array=()
-  while IFS= read -r line || [[ -n "$line" ]]; do
-      line=$(echo "$line" | sed 's/#.*//' | awk '{$1=$1};1')
-      if [ "$line" = "" ]; then
-          continue
-      fi
+    print_info "clear service_list: ${service_list}"
+    for service in "${service_list[@]}"; do
+        # remove the $service container.
+        print_stage "stop and remove container: sparrow_container_${CONTAINER_NAMESPACE}_${service}"
+        docker stop "sparrow_container_${CONTAINER_NAMESPACE}_${service}"
+        docker rm "sparrow_container_${CONTAINER_NAMESPACE}_${service}"
 
-      key=$(echo "$line" | cut -d '=' -f1)
-      value=$(echo "$line" | cut -d '=' -f2-)
-
-      if [[ $key =~ $pattern ]]; then
-          array+=("$key=$value")
-      fi
-  done < $CONST_SPARROW_CONFIG_ENV_FILE
-
-  sorted_array=($(printf "%s\n" "${array[@]}" | sort))
-  for element in "${sorted_array[@]}"; do
-    echo "$element"
-  done
+        # remove the all version images of sparrow-basic-$service/sparrow-app-$service.
+        print_stage "removing images: sparrow-basic-$service(all version), sparrow-app-$service(all version)"
+        docker images | grep "sparrow-app-$service" | awk '{print $3}' | xargs -I {} sh -c 'if [ -n "{}" ]; then docker rmi "{}"; fi'
+        # perhaps there's no need to delete the basic image; we'll see later if this operation can be removed.
+        docker images | grep "sparrow-basic-$service" | awk '{print $3}' | xargs -I {} sh -c 'if [ -n "{}" ]; then docker rmi "{}"; fi'
+    done
 }
 
-# enter command
-enter() {
-    if [ "$1" == "" ]; then
-        osascript "enter.applescript"
-        return
-    fi
+# before run sparrowtool command.
+before_sparrowtool_command() {
+    print_stage "do before_sparrowtool_command..."
+}
 
-    dir="/"
-    if [ "$1" == "nginx" ]; then
-        dir="/etc/nginx/"
-    elif [ "$1" == "kafka" ]; then
-        dir="/opt/kafka_${IMAGE_OFFICIAL_KAFKA_VERSION}/bin"
-    fi
-
-    # -u root: fix error(https://stackoverflow.com/questions/37836124/i-have-no-name-as-user-logging-into-jenkins-in-a-docker-container-that-uses-t)
-    container_name="sparrow_container_${CONTAINER_NAMESPACE}_$1"
-    print_info "docker exec -w $dir -u root -it $container_name bash"
-    docker exec -w $dir -u root -it "$container_name" bash
+# after run sparrowtool command.
+after_sparrowtool_command() {
+    print_stage "do after_sparrowtool_command..."
 }
 
 # before run sparrowtool command.
@@ -198,11 +261,10 @@ elif [ "${COMMAND}" = "new" ]; then
     new "$@"
 elif [ "${COMMAND}" = "env" ]; then
     search_env "$@"
-# not core commands.
-elif [ "${COMMAND}" = "enter" ]; then
-    enter "$2"
-elif [ "${COMMAND}" = "help" ] || [ "${COMMAND}" = "--help" ] || [ "${COMMAND}" = "h" ] || [ "${COMMAND}" = "-h" ] ; then
-    sparrowtool_help
+elif [ "${COMMAND}" = "clear" ]; then
+    clear_service "$2"
+elif [ "${COMMAND}" = "tip" ] || [ "${COMMAND}" = "tips" ]; then
+    tip
 else
     echo "not support command: ${COMMAND} (Unknown command: ${COMMAND})"
 fi
